import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FormDataService {

  constructor() { }

  formData() {
    var data = {
      "religiousCat":[
        {"cat":"Hindu","catId":1},
        {"cat":"Muslim", "catId":2},
        {"cat":"Jain", "catId":3},
        {"cat":"Christian", "catId":4},
        {"cat":"Parsi", "catId":5},
        {"cat":"Buddhist", "catId":6},
        {"cat":"Sikh", "catId":7},
        {"cat":"Other", "catId":8},
        {"cat":"Religion not Stated", "catId":8}],
      "socialCat": [{ "cat": "General", "catId": 1 },
      { "cat": "SC", "catId": 2 },
      { "cat": "ST", "catId": 3 },
      { "cat": "OBC", "catId": 4 },
      { "cat": "ORC", "catId": 5 },
      { "cat": "OTHERS", "catId": 6 }],
      "gender": [{ "gender": "Male", "genderId": 1 },
      { "gender": "Female", "genderId": 2 },
      { "gender": "Transgender", "genderId": 3 }],
      "typeOfTeacher": [{ "tchType": "Head teacher", "tchId": 1 },
      { "tchType": "Acting head teacher", "tchId": 2 },
      { "tchType": "Teacher", "tchId": 3 },
      { "tchType": "Instructor positioned as per RTE", "tchId": 5 },
      { "tchType": "Principal", "tchId": 6 },
      { "tchType": "Vice Principal", "tchId": 7 },
      { "tchType": "Lecturer", "tchId": 8 }],
      "natureOfAppointment": [{ "apntmntType": "Regular", "apntmntId": 1 },
      { "apntmntType": "Contract", "apntmntId": 2 },
      { "apntmntType": "Part-Time", "apntmntId": 3 }],
      "eduQualification": [{ "qualType": "Below secondary", "qualId": 1 },
      { "qualType": "Secondary", "qualId": 2 },
      { "qualType": "Higher secondary", "qualId": 3 },
      { "qualType": "Graduate", "qualId": 4 },
      { "qualType": "Post graduate", "qualId": 5 },
      { "qualType": "M.Phil.", "qualId": 6 },
      { "qualType": "Ph.D.", "qualId": 7 },
      { "qualType": "Post Doctoral", "qualId": 8 }],
      "profQualification": [{ "profQualType": "Diploma or certificate in basic teachers’ training of a duration not less than two years", "profQualId": 1 },
      { "profQualType": "Bachelor of Elementary Education (B.El.Ed.)", "profQualId": 2 },
      { "profQualType": " B.Ed. or equivalent", "profQualId": 3 },
      { "profQualType": "M.Ed. or equivalent", "profQualId": 4 },
      { "profQualType": "Others", "profQualId": 5 },
      { "profQualType": "None", "profQualId": 6 },
      { "profQualType": "Diploma/degree in special education", "profQualId": 7 },
      { "profQualType": "Pursuing any relevant professional course", "profQualId": 8 }],
      "classTaught": [{ "clsTaughtType": "Primary only", "clsTaughtId": 1 },
      { "clsTaughtType": "Upper primary only", "clsTaughtId": 2 },
      { "clsTaughtType": "Primary and Upper Primary", "clsTaughtId": 3 },
      { "clsTaughtType": "Secondary only", "clsTaughtId": 5 },
      { "clsTaughtType": "Higher Secondary only", "clsTaughtId": 6 },
      { "clsTaughtType": "Upper primary and Secondary", "clsTaughtId": 7 },
      { "clsTaughtType": "Secondary and Higher Secondary", "clsTaughtId": 8 },
      { "clsTaughtType": "Pre-Primary Only", "clsTaughtId": 10 },
      { "clsTaughtType": "Pre- Primary & Primary", "clsTaughtId": 11 }],
      "subjects": [{ "subjectType": "All subjects", "subjectId": 1 },
      { "subjectType": "Language(if teaching more than one language)", "subjectId": 2 },
      { "subjectType": "Mathematics", "subjectId": 3 },
      { "subjectType": "Environment studies", "subjectId": 4 },
      { "subjectType": "Sports", "subjectId": 5 },
      { "subjectType": "Music", "subjectId": 6 },
      { "subjectType": "Science", "subjectId": 7 },
      { "subjectType": "Social studies", "subjectId": 8 },
      { "subjectType": "Accountancy", "subjectId": 10 },
      { "subjectType": "Biology", "subjectId": 11 },
      { "subjectType": "Business Studies", "subjectId": 12 },
      { "subjectType": "Chemistry", "subjectId": 13 },
      { "subjectType": "Computer Science", "subjectId": 14 },
      { "subjectType": "Economics", "subjectId": 15 },
      { "subjectType": "Engineering Drawing", "subjectId": 16 },
      { "subjectType": "Fine Arts", "subjectId": 17 },
      { "subjectType": "Geography", "subjectId": 18 },
      { "subjectType": "History", "subjectId": 19 },
      { "subjectType": "Home Science", "subjectId": 20 },
      { "subjectType": "Philosophy", "subjectId": 21 },
      { "subjectType": "Physics", "subjectId": 22 },
      { "subjectType": "Political Science", "subjectId": 23 },
      { "subjectType": "Psychology", "subjectId": 24 },
      { "subjectType": "Foreign Language", "subjectId": 25 },
      { "subjectType": "Botany", "subjectId": 26 },
      { "subjectType": "Zoology", "subjectId": 27 },
      { "subjectType": "Hindi", "subjectId": 41 },
      { "subjectType": "Sanskrit", "subjectId": 43 },
      { "subjectType": "Urdu", "subjectId": 45 },
      { "subjectType": "English", "subjectId": 46 },
      { "subjectType": "Regional Language", "subjectId": 47 },
      { "subjectType": "Art education", "subjectId": 91 },
      { "subjectType": "Health& physical education", "subjectId": 92 },
      { "subjectType": "Work education", "subjectId": 93 },
      { "subjectType": "Other subjects", "subjectId": 0 }
      ],
      "training": [{ "trngType": "Not required", "trngId": 0 },
      { "trngType": "Subject knowledge", "trngId": 1 },
      { "trngType": "Pedagogical issues", "trngId": 2 },
      { "trngType": "ICT Skills", "trngId": 3 },
      { "trngType": "Knowledge and skills to engage with CWSN", "trngId": 4 },
      { "trngType": "Leadership and management skills", "trngId": 5 },
      { "trngType": "Sanitation & Hygiene", "trngId": 6 },
      { "trngType": "Others", "trngId": 7 }],
      "disability": [
      { "disabilityType": "Visually Handicapped", "disabilityId": 1 },
      { "disabilityType": "Hearing Impairment", "disabilityId": 2 },      
      { "disabilityType": "Physically Disabled", "disabilityId": 3 }],

      "transferGround": [
        { "transferGroundType": "Request Transfer General", "transferGroundId": 1 },
        { "transferGroundType": "Request On LTR", "transferGroundId": 2 },      
        { "transferGroundType": "Request On MDG", "transferGroundId": 3 },
        { "transferGroundType": "Request On DFP", "transferGroundId": 4 },
        { "transferGroundType": "Request On PH", "transferGroundId": 5 },
        { "transferGroundType": "Request On Spouse Ground", "transferGroundId": 6 },
        { "transferGroundType": "Surplus", "transferGroundId": 7 },
        { "transferGroundType": "Displacement", "transferGroundId": 8 },
        { "transferGroundType": "ADMN Ground Under PARA7(E)", "transferGroundId": 9 },
        { "transferGroundType": "ADMN Ground Under 40 Years Of Age", "transferGroundId": 10 },
        { "transferGroundType": "Direct Recruitment", "transferGroundId": 11 },
        { "transferGroundType": "Promotion", "transferGroundId": 12 },
        { "transferGroundType": "Request On SP", "transferGroundId": 13 },
        { "transferGroundType": "Request On Widow/Widower", "transferGroundId": 14 },
        { "transferGroundType": "Mutual Transfer", "transferGroundId": 15 },
        { "transferGroundType": "Request On Any Other Ground", "transferGroundId": 16 },
        { "transferGroundType": "No Taker Vacancy Availed", "transferGroundId": 17 },
        { "transferGroundType": "Any Other Administrative Ground", "transferGroundId": 18 },
        { "transferGroundType": "Transfer Cancellation", "transferGroundId": 19 }],
        
      
      "yesNo": [{ "responseType": "Yes", "responseId": 1 },
      { "responseType": "No", "responseId": 2 }]
    }
    return data;
  }
}
